apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - release.yaml

configMapGenerator:
  - name: prometheus-node-exporter-values
    files:
      - values.yaml

configurations:
  - kustomize-configurations.yaml