---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: node-exporter
spec:
  interval: 10m
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-node-exporter
spec:
  interval: 5m
  chart:
    spec:
      chart: prometheus-node-exporter
      version: 4.43.1
      sourceRef:
        kind: HelmRepository
        name: node-exporter
      interval: 10m
  valuesFrom:
    - kind: ConfigMap
      name: prometheus-node-exporter-values
      valuesKey: values.yaml