apiVersion: applications.authentik.crossplane.io/v1alpha1
kind: ForwardAuth
metadata:
  name: alertmanager
  labels:
    "crossplane.io/claim-name": "alertmanager"
    "crossplane.io/claim-namespace": "observability"
spec:
  externalHost: "grocy.example.com"
  icon: "https://avatars.githubusercontent.com/u/3380462?s=200&v=4"
  description: "https://prometheus.io/docs/alerting/latest/alertmanager/"
  backendService:
    name: vmalertmanager-vmks-victoria-metrics-k8s-stack
    port: 9093
