---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crds
  namespace: flux-system
spec:
  interval: 10m0s
  path: system/crds
  prune: false
  targetNamespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

