---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crossplane-configurations
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./system/controllers/crossplane-configurations/${CLUSTER_NAME}
  targetNamespace: crossplane-system
  prune: true
  dependsOn:
    - name: crossplane-addons
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substitute:
      CLUSTER_NAME: ${CLUSTER_NAME}
      ACTUAL_CLUSTER: ${ACTUAL_CLUSTER}
