---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crossplane-addons
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./system/controllers/crossplane-addons/${ENVIRONMENT}/${CLUSTER_NAME}
  targetNamespace: crossplane-system
  prune: true
  dependsOn:
    - name: crds
    - name: namespaces
    - name: crossplane
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substitute:
      ENVIRONMENT: ${ENVIRONMENT}
      CLUSTER_NAME: ${CLUSTER_NAME}

