---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: snapshot-controller
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./system/controllers/snapshot-controller/${ENVIRONMENT}/${CLUSTER_NAME}
  targetNamespace: kube-system
  prune: true
  dependsOn:
    - name: crds
    - name: namespaces
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

