---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./system/controllers/traefik/${ENVIRONMENT}/${CLUSTER_NAME}
  targetNamespace: traefik
  prune: true
  dependsOn:
    - name: crds
    - name: namespaces
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substitute:
      ENVIRONMENT: ${ENVIRONMENT}
      CLUSTER_NAME: ${CLUSTER_NAME}
    substituteFrom:
      - kind: Secret
        name: base-domain
