---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: velero
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./system/controllers/velero/${CLUSTER_NAME}
  targetNamespace: velero
  prune: true
  dependsOn:
    - name: crds
    - name: namespaces
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substitute:
      CLUSTER_NAME: ${CLUSTER_NAME}
      ACTUAL_CLUSTER: ${ACTUAL_CLUSTER}
    substituteFrom:
      - kind: Secret
        name: base-domain
