---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: robusta
  namespace: robusta
spec:
  chart:
    spec:
      chart: robusta
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: robusta
      version: 0.20.0
  interval: 1m0s
  valuesFrom:
    - kind: Secret
      name: robusta-values
  values:
    globalConfig: # this line should already exist
      # add the lines below
      alertmanager_url: "http://vmalertmanager-vmks-victoria-metrics-k8s-stack.observability.svc.cluster.local:9093"
      grafana_url: ""
      prometheus_url: "http://vmsingle-vmks-victoria-metrics-k8s-stack.observability.svc.cluster.local:8429"
    clusterName: ${ENVIRONMENT}
    kubewatch:
      securityContext:
        container:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsUser: 1000
        pod:
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
    runner:
      resources:
        limits:
          cpu: null
        requests:
          cpu: 250m
          memory: 512Mi
      securityContext:
        container:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsUser: 65534
        pod:
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
