---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: robusta
  namespace: robusta
spec:
  chart:
    spec:
      chart: robusta
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: robusta
      version: 0.20.0
  interval: 1m0s
  valuesFrom:
    - kind: Secret
      name: robusta-values
  values:
    kubewatch:
      securityContext:
        container:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsUser: 1000
        pod:
          seccompProfile:
            type: RuntimeDefault
    runner:
      resources:
        limits:
          cpu: null
        requests:
          cpu: 250m
          memory: 512Mi
      securityContext:
        container:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
        pod:
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
