version: '3'

vars:
  CLUSTER_NAME:
    sh: if [ -n "$ENVIRONMENT" ]; then echo "$ENVIRONMENT" ; else exit 1 ; fi

tasks:
  destroy:
    cmds:
      - for ks in $(kubectl get kustomization --no-headers -o custom-columns=":metadata.name" -n flux-system); do flux suspend kustomization $ks ; done
      - kubectl --namespace flux-system delete helmrelease traefik
      - for: ["domain", "observability", "traefik" ]
        cmd: kubectl delete kustomization {{ .ITEM }} -n flux-system
  apply-infra:
    cmds:
      - cd provision/{{ .CLUSTER_NAME }} && terraform apply
  destroy-infra:
    cmds:
      - cd provision && terraform state rm 'module.kubernetes.talos_machine_configuration_apply.worker'
      - cd provision && terraform state rm 'module.kubernetes.talos_machine_configuration_apply.control_plane'
      - cd provision && terraform state rm 'module.kubernetes.talos_machine_secrets.this'
      - cd provision && terraform destroy