version: '3'

vars:
  ENVIRONMENT:
    sh: if [ -n "$ENVIRONMENT" ]; then echo "$ENVIRONMENT" ; else exit 1 ; fi
  CLUSTER_NAME:
    sh: if [ -n "$CLUSTER_NAME" ]; then echo "$CLUSTER_NAME" ; else exit 1 ; fi

tasks:
  reconcile:
    cmds:
      - flux reconcile kustomization crds --with-source
      - flux reconcile kustomization crossplane
      - flux reconcile kustomization crossplane-addons
      - flux reconcile kustomization crossplane-custom-config
  generate:
    cmds:
      - kcl run ./crossplane/kcl/forward-auth/crossplane.k > ./crossplane/rendered/forward-auth.yaml
      - kcl run ./crossplane/kcl/oauth-app/crossplane.k > ./crossplane/rendered/oauth-app.yaml
      - kcl run ./crossplane/kcl/ldap-provider/crossplane.k > ./crossplane/rendered/ldap-provider.yaml
      - kcl run ./crossplane/kcl/https-ingress/crossplane.k > ./crossplane/rendered/https-ingress.yaml
  destroy:
    cmds:
      - for ks in $(kubectl get kustomization --no-headers -o custom-columns=":metadata.name" -n flux-system); do flux suspend kustomization $ks ; done
      - kubectl --namespace flux-system delete helmrelease traefik
      - for: ["domain", "observability", "traefik" ]
        cmd: kubectl delete kustomization {{ .ITEM }} -n flux-system
  apply-infra:
    cmds:
      - cd provision/{{ .ENVIRONMENT }}/{{ .CLUSTER_NAME }} && terraform apply

  bootstrap:
    cmds:
      - kubectl apply -f clusters/{{ .ENVIRONMENT }}/{{ .CLUSTER_NAME }}/system.yaml
      - flux reconcile kustomization crds --with-source
      - flux reconcile kustomization crossplane --with-source
      - flux reconcile kustomization flux-patch --with-source
  destroy-infra:
    cmds:
#      - cd provision/{{ .ENVIRONMENT }}/{{ .CLUSTER_NAME }} && terraform state rm module.kubernetes.talos_machine_configuration_apply.worker
#      - cd provision/{{ .ENVIRONMENT }}/{{ .CLUSTER_NAME }} && terraform state rm module.cluster.module.kubernetes.talos_machine_configuration_apply.control_plane
#      - cd provision/{{ .ENVIRONMENT }}/{{ .CLUSTER_NAME }} && terraform state rm 'module.kubernetes.talos_machine_secrets.this'
      - cd provision/{{ .ENVIRONMENT }}/{{ .CLUSTER_NAME }} && terraform destroy