apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#- kyverno
- velero
- victoria-metrics
- prometheus-operator
- grafana-operator
- external-secrets-operator
- cloudnative-pg
- keycloak
- volumesnapshotter