---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboards: "grafana"
spec:
  config:
    plugins:
      allow_loading_unsigned_plugins: victoriametrics-datasource,victoriametrics-logs-datasource
    security:
      admin_user: root
      admin_password: secret
  deployment:
    spec:
      template:
        spec:
          securityContext:
            seccompProfile:
              type: RuntimeDefault
          containers:
            - name: grafana
              resources:
                requests:
                  cpu: 100m
                  memory: 150Mi
              securityContext:
                # Customize this in case your volume provider needs specific UIDs/GIDs
                runAsUser: 1001
                runAsGroup: 1001
                runAsNonRoot: true
                allowPrivilegeEscalation: false
                capabilities:
                  drop: ["ALL"]
              readinessProbe:
                failureThreshold: 3
