apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - velero-release.yaml
  - secrets.yaml

configMapGenerator:
  - files:
      - values.yaml
    name: velero-values

configurations:
  - kustomize-configurations.yaml

namespace: velero
