apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backupstoragelocation-default.yaml
- clusterrolebinding-velero.yaml
- deployment-velero.yaml
- namespace-velero.yaml
- secret-cloud-credentials.yaml
- serviceaccount-velero.yaml
- volumesnapshotlocation-default.yaml
