---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloud-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-store
  target:
    name: cloud-credentials
    template:
      engineVersion: v2
      data:
        cloud: |
          [default]
          aws_access_key_id={{ .key }}
          aws_secret_access_key={{ .secret }}
  data:
    - secretKey: key
      remoteRef:
        key: hetzner-object-store-staging
        property: access_key
    - secretKey: secret
      remoteRef:
        key: hetzner-object-store-staging
        property: secret_key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: velero-repo-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-store
  target:
    name: velero-repo-credentials
  data:
    - remoteRef:
        key: velero-repo-password
        property: password
      secretKey: repository-password