---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: crossplane
spec:
  interval: 10m
  url: https://charts.crossplane.io/stable
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: crossplane
spec:
  interval: 10m
  chart:
    spec:
      chart: crossplane
      version: 1.18.2
      sourceRef:
        kind: HelmRepository
        name: crossplane
      interval: 10m
  valuesFrom:
    - kind: ConfigMap
      name: crossplane-values
