apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crossplane-system
resources:
  - helmrelease.yaml

configMapGenerator:
  - name: crossplane-values
    files:
      - values.yaml=values.yaml

configurations:
  - kustomize-configurations.yaml