---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: victoria-metrics-operator
  namespace: flux-system
spec:
  interval: 10m0s
  path: manifests/controllers/victoria-metrics
  targetNamespace: victoria-metrics
  prune: true
  dependsOn:
    - name: crds
    - name: namespaces
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-env
