apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: goauthentik
spec:
  interval: 10m
  url: https://charts.goauthentik.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
spec:
  interval: 5m
  chart:
    spec:
      chart: authentik
      version: 2024.12.2
      sourceRef:
        kind: HelmRepository
        name: goauthentik
      interval: 10m
  valuesFrom:
    - kind: ConfigMap
      name: authentik-values
      valuesKey: values.yaml
