---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-database
  labels:
    app.kubernetes.io/part-of: authentik
    app.kubernetes.io/component: database
spec:
  instances: 3
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    major: 16
    name: postgresql
  monitoring:
    enablePodMonitor: true
  storage:
    size: 1Gi
  inheritedMetadata:
    labels:
      app.kubernetes.io/part-of: authentik
      app.kubernetes.io/component: database
  backup:
    barmanObjectStore:
      destinationPath: "s3://fzx-staging-postgres/backup-authentik-v2"
      endpointURL: https://nbg1.your-objectstorage.com
      wal:
        compression: gzip
      data:
        compression: gzip
      s3Credentials:
        accessKeyId:
          name: hetzner-object-store
          key: access_key
        secretAccessKey:
          name: hetzner-object-store
          key: secret_key
    retentionPolicy: "30d"

  bootstrap:
    recovery:
      source: clusterBackup

  externalClusters:
    - name: clusterBackup
      barmanObjectStore:
        serverName: authentik
        destinationPath: "s3://fzx-staging-postgres/backup-authentik-v1"
        endpointURL: https://nbg1.your-objectstorage.com
        s3Credentials:
          accessKeyId:
            name: hetzner-object-store
            key: access_key
          secretAccessKey:
            name: hetzner-object-store
            key: secret_key
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: authentik-database
  labels:
    app.kubernetes.io/part-of: authentik
    app.kubernetes.io/component: database
spec:
  immediate: true
  schedule: "0 0 3 * * *"
  backupOwnerReference: cluster
  cluster:
    name: authentik-database
