---
kind: HTTPSIngressClaim
apiVersion: custom.fzx.dev/v1alpha1
metadata:
  name: authentik
spec:
  externalHost: authentik.${BASE_DOMAIN}
  backendService:
    name: authentik-server
    port: 80
  middleware:
    - type: ResponseHeaderModifier
      responseHeaderModifier:
        add:
          - name: Content-Security-Policy
            value: "default-src 'self'; img-src https: http: data:; object-src 'none'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline';"
