apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik
resources:
  - provision
  - authentik-release.yaml
  - dashboard.yaml
  - redis.yaml
  - secrets.yaml
  - ingress.yaml
  - database.yaml
  - traefik-app.yaml
  - s3-creds.yaml

configMapGenerator:
  - name: authentik-values
    files:
      - values.yaml=values.yaml

configurations:
  - kustomize-configurations.yaml