apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - authentik-release.yaml
  - dashboard.yaml
  - redis.yaml
  - secrets.yaml
  - ingress.yaml

configMapGenerator:
  - name: authentik-values
    files:
      - values.yaml=values.yaml

configurations:
  - kustomize-configurations.yaml