---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-key
spec:
  secretStoreRef:
    name: cluster-store
    kind: ClusterSecretStore
  target:
    name: authentik-key
  data:
    - secretKey: secret
      remoteRef:
        key: authentik-secret-key
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-bootstrap-password
spec:
  secretStoreRef:
    name: cluster-store
    kind: ClusterSecretStore
  target:
    name: authentik-bootstrap-password
  data:
    - secretKey: password
      remoteRef:
        property: password
        key: authentik-bootstrap-password
    - secretKey: email
      remoteRef:
        property: username
        key: authentik-bootstrap-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-bootstrap-token
spec:
  secretStoreRef:
    name: cluster-store
    kind: ClusterSecretStore
  target:
    name: authentik-bootstrap-token
  data:
    - secretKey: token
      remoteRef:
        key: authentik-bootstrap-token
        property: password
