global:
  env:
    - name: AUTHENTIK_AVATARS
      value: gravatar
    - name: AUTHENTIK_REDIS__HOST
      value: authentik-redis-master
    - name: AUTHENTIK_REDIS__PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: redis-password
    - name: AUTHENTIK_POSTGRESQL__HOST
      valueFrom:
        secretKeyRef:
          key: host
          name: authentik-database-app
    - name: AUTHENTIK_POSTGRESQL__PORT
      valueFrom:
        secretKeyRef:
          key: port
          name: authentik-database-app
    - name: AUTHENTIK_POSTGRESQL__NAME
      valueFrom:
        secretKeyRef:
          key: dbname
          name: authentik-database-app
    - name: AUTHENTIK_POSTGRESQL__USER
      valueFrom:
        secretKeyRef:
          key: username
          name: authentik-database-app
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: authentik-database-app

    - name: AUTHENTIK_SECRET_KEY
      valueFrom:
        secretKeyRef:
          key: secret
          name: authentik-key
    - name: AUTHENTIK_BOOTSTRAP_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: authentik-bootstrap-password
    - name: AUTHENTIK_BOOTSTRAP_EMAIL
      valueFrom:
        secretKeyRef:
          key: email
          name: authentik-bootstrap-password
    - name: AUTHENTIK_BOOTSTRAP_TOKEN
      valueFrom:
        secretKeyRef:
          key: token
          name: authentik-bootstrap-token

  volumeMounts:
    - name: media
      mountPath: /media
  volumes:
    - name: media
      emptyDir: { }

authentik:
  log_level: info
  postgresql:
    host: null
    name: null
    user: null
    password: null
    port: null
  redis:
    host: null
    password: null

server:
  deploymentAnnotations:
    terasky.backstage.io/dependsOn: "component:authentik-database"
  resources:
    requests:
      cpu: 100m
      memory: 640Mi
    limits:
      memory: 640Mi

  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault


  # -- authentik server container-level security context
  # @default -- See [values.yaml]
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

worker:
  deploymentAnnotations:
    terasky.backstage.io/dependsOn: "resource:authentik-database"
  resources:
    requests:
      cpu: 100m
      memory: 640Mi
    limits:
      memory: 640Mi

  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true

prometheus:
  rules:
    enabled: true
