---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: domain
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/domain
  targetNamespace: crossplane-system
  prune: true
  dependsOn:
    - name: crossplane-configurations
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substitute:
      ENVIRONMENT: ${ENVIRONMENT}
      CLUSTER_NAME: ${CLUSTER_NAME}
    substituteFrom:
      - kind: Secret
        name: base-domain
