---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pgadmin
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/pgadmin/${ENVIRONMENT}
  prune: true
  dependsOn:
    - name: crds
  targetNamespace: pgadmin
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substitute:
      ENVIRONMENT: ${ENVIRONMENT}
      CLUSTER_NAME: ${CLUSTER_NAME}
      ACTUAL_CLUSTER: ${ACTUAL_CLUSTER}
    substituteFrom:
      - kind: Secret
        name: base-domain
