---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: robusta
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/robusta/${ENVIRONMENT}/${ACTUAL_CLUSTER}
  prune: true
  dependsOn:
    - name: crds
  targetNamespace: robusta
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substitute:
      ENVIRONMENT: ${ENVIRONMENT}
      CLUSTER_NAME: ${CLUSTER_NAME}
      ACTUAL_CLUSTER: ${ACTUAL_CLUSTER}
