apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vm-k8s-stack.yaml
  - alertmanager-config.yaml
  - ingress.yaml

configMapGenerator:
  - name: victoria-metrics-k8s-stack-values
    files:
      - values.yaml=vm-k8s-stack-values.yaml