---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crossplane
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/controllers/crossplane/${CLUSTER_NAME}
  targetNamespace: crossplane-system
  prune: true
  dependsOn:
    - name: crds
    - name: namespaces
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  healthChecks:
    - kind: Deployment
      name: crossplane
      namespace: crossplane-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-env
