---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-operator
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./system/controllers/grafana-operator/${CLUSTER_NAME}
  targetNamespace: grafana-operator
  prune: true
  dependsOn:
    - name: crds
    - name: namespaces
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substitute:
      CLUSTER_NAME: ${CLUSTER_NAME}
      BASE_DOMAIN: ${BASE_DOMAIN}
