apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
spec:
  instances: 1
  db:
    vendor: postgres
    host: keycloak-database-rw
    database: app
    port: 5432
    usernameSecret:
      name: keycloak-database-app
      key: username
    passwordSecret:
      name: keycloak-database-app
      key: password
  http:
    tlsSecret: tls-keycloak-ingress
  hostname:
    hostname: keycloak.${BASE_DOMAIN}
  proxy:
    headers: xforwarded # double check your reverse proxy sets and overwrites the X-Forwarded-* headers
