---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: jacobcolvin-provider-authentik
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          containers:
            - name: package-runtime
              resources:
                requests:
                  cpu: 20m
                  memory: 768Mi
                limits:
                  memory: 768Mi

---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: jacobcolvin-provider-authentik
spec:
  ignoreCrossplaneConstraints: false
  package: felixz92/provider-authentik:v0.3.1
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1
  runtimeConfigRef:
    apiVersion: pkg.crossplane.io/v1beta1
    kind: DeploymentRuntimeConfig
    name: jacobcolvin-provider-authentik
  skipDependencyResolution: false