apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - traefik-release.yaml

configMapGenerator:
  - name: victoria-metrics-operator-values
    files:
      - values.yaml=values.yaml

configurations:
  - kustomize-configurations.yaml