apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak
resources:
  - operator.yaml
patches:
  - path: seccomp.yaml
    target:
      group: apps
      kind: Deployment
      version: v1
