---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keycloak
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./apps/keycloak/${CLUSTER_NAME}
  prune: true
  dependsOn:
    - name: crds
  targetNamespace: keycloak
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substitute:
      CLUSTER_NAME: ${CLUSTER_NAME}
    substituteFrom:
      - kind: Secret
        name: base-domain
