namespace: grafana-operator

resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: seccomp.yaml
  target:
    group: apps
    kind: Deployment
    version: v1
