apiVersion: custom.fzx.devo/v1alpha1
kind: HTTPSIngressClaim
metadata:
  name: alertmanager
  labels:
    "crossplane.io/claim-name": "alertmanager"
    "crossplane.io/claim-namespace": "observability"
spec:
  externalHost: "grocy.example.com"
  backendService:
    name: vmalertmanager-vmks-victoria-metrics-k8s-stack
    port: 9093
  middleware:
    - extensionRef:
        group: traefik.io
        kind: Middleware
        name: alertmanager-middleware
      type: ExtensionRef
