---
kind: xHTTPSIngress
apiVersion: custom.fzx.dev/v1alpha1
metadata:
  name: httpsingressclaim-sample
spec:
  externalHosts:
  - name: example.com
    cname: example-cluster-1.com
  - name: example2.com
    cname: example-cluster-2.com
  backendService:
    name: backend-service
    port: 80
#  middleware:
#    - sadad: asdsd
#      asdsd: dasd
#      sadasd: asd
