---
kind: HTTPSIngressClaim
apiVersion: custom.fzx.dev/v1alpha1
metadata:
  name: httpsingressclaim-sample
spec:
  externalHost: whoami.${BASE_DOMAIN}
  clusterName: ${CLUSTER_NAME}
  backendService:
    name: whoami
    port: 9000
#  middleware:
#    - sadad: asdsd
#      asdsd: dasd
#      sadasd: asd
