---
apiVersion: provider.authentik.crossplane.io/v1alpha1
kind: OAuth2
metadata:
  name: grafana
spec:
  writeConnectionSecretToRef:
    name: grafana-client-secret
    namespace: observability
  forProvider:
    clientId: grafana
    name: grafana
    authorizationFlowRef:
      name: default-provider-authorization-implicit-consent
    invalidationFlowRef:
      name: default-provider-invalidation-flow
    allowedRedirectUris:
      - matching_mode: strict
        url: https://grafana.staging-fzx-infra.dev/login/generic_oauth
  providerConfigRef:
    name: authentik-provider
---
apiVersion: authentik.crossplane.io/v1alpha1
kind: Application
metadata:
  name: grafana
spec:
  providerConfigRef:
    name: authentik-provider
  forProvider:
    name: Grafana
    protocolProvider: 1
    metaIcon: "https://cdn.worldvectorlogo.com/logos/grafana.svg"
    metaDescription: "https://grafana.com/docs/grafana/latest/"
    metaLaunchUrl: https://grafana.staging-fzx-infra.dev
---
apiVersion: policy.authentik.crossplane.io/v1alpha1
kind: Binding
metadata:
   name: grafana-access
spec:
  forProvider:
    target:
#---
#apiVersion: authentik.crossplane.io/v1alpha1
#kind: Application
#metadata:
#  name: name
#spec:
#  forProvider:
#    name: test app
#    protocolProvider: ${authentik_provider_oauth2.name.id}