---
apiVersion: provider.authentik.crossplane.io/v1alpha1
kind: OAuth2
metadata:
  name: grafana
  annotations:
    crossplane.io/external-name: "2"
spec:
  writeConnectionSecretToRef:
    name: grafana-client-secret
    namespace: observability
  forProvider:
    clientId: grafana
    name: grafana
    propertyMappingsRefs:
      - name: openid-email
      - name: openid-openid
      - name: openid-profile
    authorizationFlowRef:
      name: default-provider-authorization-implicit-consent
    invalidationFlowRef:
      name: default-provider-invalidation-flow
    allowedRedirectUris:
      - matching_mode: strict
        url: https://grafana.staging-fzx-infra.dev/login/generic_oauth
  providerConfigRef:
    name: authentik-provider
---
apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: grafana-oauth-application
spec:
  providerConfigRef:
    name: kubernetes-provider
  references:
    - patchesFrom:
        apiVersion: provider.authentik.crossplane.io/v1alpha1
        kind: OAuth2
        name: grafana
        fieldPath: status.atProvider.id
      toFieldPath: spec.forProvider.manifest.spec.forProvider.protocolProvider
  forProvider:
    manifest:
      apiVersion: authentik.crossplane.io/v1alpha1
      kind: Application
      metadata:
        name: grafana
        annotations:
          crossplane.io/external-name: grafana
      spec:
        providerConfigRef:
          name: authentik-provider
        forProvider:
          name: Grafana
          protocolProvider: 2
          metaIcon: "https://cdn.worldvectorlogo.com/logos/grafana.svg"
          metaDescription: "https://grafana.com/docs/grafana/latest/"
          metaLaunchUrl: https://grafana.staging-fzx-infra.dev
