apiVersion: directory.authentik.crossplane.io/v1alpha1
kind: Group
metadata:
  name: cluster-admins
  annotations:
    crossplane.io/external-name: cabab51f-a3b7-46fc-bdad-9c3488492397
spec:
  forProvider:
    name: cluster-admins
    isSuperuser: false
  providerConfigRef:
    name: authentik-provider