apiVersion: authentik.crossplane.io/v1alpha1
kind: ServiceConnectionKubernetes
metadata:
  name: local
  annotations:
    crossplane.io/external-name: 96895c1a-1d60-492f-8e7d-c5a7c32ce5a7
spec:
  forProvider:
    local: true
    name: local
  providerConfigRef:
    name: authentik-provider