apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - groups.yaml
  - k8sconnection.yaml
  - scopes.yaml

patches:
  - target:
      kind: Group
      name: cluster-admins
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          crossplane.io/external-name: cabab51f-a3b7-46fc-bdad-9c3488492397