---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: certificate-authority
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./system/certificate-authority/${ENVIRONMENT}/${CLUSTER_NAME}
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substitute:
      ENVIRONMENT: ${ENVIRONMENT}
      CLUSTER_NAME: ${CLUSTER_NAME}
    substituteFrom:
      - kind: Secret
        name: lets-encrypt-email