---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-patch
spec:
  interval: 10m0s
  path: system/controllers/flux
  prune: true
  targetNamespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

