apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- pvc.yaml
- secrets.yaml
- service.yaml
- serviceaccount.yaml
- servicemonitor.yaml
- ingress.yaml

configMapGenerator:
  - name: zot-config
    files:
      - config.json