---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zot-htpasswd
spec:
  secretStoreRef:
    name: cluster-store
    kind: ClusterSecretStore
  target:
    name: zot-htpasswd
    template:
      data:
        htpasswd: |-
          {{ htpasswd .adminUser .adminPassword }}
          {{ htpasswd .pushUser .pushPassword }}
          {{ htpasswd .pullUser .pullPassword }}
  data:
    - secretKey: adminUser
      remoteRef:
        key: zot-admin-user
        property: username
    - secretKey: adminPassword
      remoteRef:
        key: zot-admin-user
        property: password
    - secretKey: pushUser
      remoteRef:
        key: zot-push-user
        property: username
    - secretKey: pushPassword
      remoteRef:
        key: zot-push-user
        property: password
    - secretKey: pullUser
      remoteRef:
        key: zot-pull-user
        property: username
    - secretKey: pullPassword
      remoteRef:
        key: zot-pull-user
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: registry-s3-secret
spec:
  secretStoreRef:
    name: cluster-store
    kind: ClusterSecretStore
  target:
    name: registry-s3-secret
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: hetzner-object-store-staging
        property: access_key
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: hetzner-object-store-staging
        property: secret_key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zot-liveness-secret
spec:
  secretStoreRef:
    name: cluster-store
    kind: ClusterSecretStore
  target:
    name: zot-liveness-secret
    template:
      data:
        HEALTHCHECK_AUTH: '{{ printf "%s:%s" .pullUser .pullPassword | b64enc }}'
  data:
    - secretKey: pullUser
      remoteRef:
        key: zot-pull-user
        property: username
    - secretKey: pullPassword
      remoteRef:
        key: zot-pull-user
        property: password
