---
# Source: zot/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: zot
  labels:
    app.kubernetes.io/name: zot
    app.kubernetes.io/instance: zot
    app.kubernetes.io/version: "v2.1.2"
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: zot
      protocol: TCP
      name: zot
  selector:
    app.kubernetes.io/name: zot
    app.kubernetes.io/instance: zot
