---
apiVersion: applications.authentik.crossplane.io/v1alpha1
kind: LDAPProviderClaim
metadata:
  name: ocis
  labels:
    "crossplane.io/claim-name": "ocis"
    "crossplane.io/claim-namespace": "ocis"
spec:
  externalHost: "ocis.example.com"
  clusterName: ${CLUSTER_NAME}
  icon: "https://avatars.githubusercontent.com/u/1645051?s=200&v=4"
  description: "https://owncloud.dev/"
  redirectURL: /oidc-callback.html
  backendService:
    name: ocis
    port: 9200
