---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zot-liveness-secret
spec:
  secretStoreRef:
    name: cluster-store
    kind: ClusterSecretStore
  target:
    name: zot-liveness-secret
    template:
      data:
        HEALTHCHECK_AUTH: '{{ printf "%s:%s" .pullUser .pullPassword | b64enc }}'
  data:
    - secretKey: pullUser
      remoteRef:
        key: zot-pull-user
        property: username
    - secretKey: pullPassword
      remoteRef:
        key: zot-pull-user
        property: password
