apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - ../base

patches:
  - target:
      kind: Deployment
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          limits:
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 64Mi
  - target:
      kind: Deployment
      name: kustomize-controller
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          limits:
            memory: 300Mi
          requests:
            cpu: 10m
            memory: 300Mi
