apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- ingress.yaml

configMapGenerator:
  - name: pgadmin-config
    files:
      - servers.json

commonLabels:
  app.kubernetes.io/name: pgadmin
  app.kubernetes.io/instance: pgadmin
