apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crossplane-system
resources:
  - ../../base
  - authentik.yaml
patches:
  - path: functions.yaml
  - path: delete-provider.yaml
  - path: delete-providercfg.yaml
  - path: provider.yaml
