apiVersion: v1
kind: Service
metadata:
  name: op-connect
spec:
  selector:
    app.kubernetes.io/name: op-connect
  ports:
    - name: connect-api
      port: 8080
      targetPort: connect-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: op-connect
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: op-connect
  template:
    metadata:
      labels:
        app.kubernetes.io/name: op-connect
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
        fsGroup: 999
      volumes:
        - name: shared-data
          emptyDir: {}
        - name: credentials
          secret:
            secretName: op-credentials
      containers:
        - name: connect-api
          image: 1password/connect-api:1.5.7
          resources:
            requests:
              memory: "100Mi"
              cpu: "0.1"
            limits:
              memory: "100Mi"
          ports:
            - name: connect-api
              containerPort: 8080
          env:
            - name: OP_SESSION
              value: /home/opuser/.config/1password-credentials.json
          volumeMounts:
            - mountPath: /home/opuser/.op/data
              name: shared-data
            - mountPath: /home/opuser/.config
              name: credentials
              readOnly: true
          livenessProbe:
            httpGet:
              path: /heartbeat
              port: connect-api
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health
              port: connect-api
            initialDelaySeconds: 5
            periodSeconds: 5
          securityContext:
            runAsUser: 999
            runAsGroup: 999
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
        - name: connect-sync
          image: 1password/connect-sync:1.5.7
          resources:
            requests:
              memory: "100Mi"
              cpu: "0.1"
            limits:
              memory: "100Mi"
          ports:
            - name: connect-sync
              containerPort: 8081
          env:
            - name: OP_SESSION
              value: /home/opuser/.config/1password-credentials.json
            - name: OP_HTTP_PORT
              value: "8081"
          volumeMounts:
            - mountPath: /home/opuser/.op/data
              name: shared-data
            - mountPath: /home/opuser/.config
              name: credentials
              readOnly: true
          livenessProbe:
            httpGet:
              path: /heartbeat
              port: connect-sync
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health
              port: connect-sync
            initialDelaySeconds: 5
            periodSeconds: 5
          securityContext:
            runAsUser: 999
            runAsGroup: 999
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
