---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-secrets
spec:
  interval: 10m
  url: https://charts.external-secrets.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
spec:
  interval: 10m
  chart:
    spec:
      chart: external-secrets
      version: 0.12.1
      sourceRef:
        kind: HelmRepository
        name: external-secrets
      interval: 10m
  values:
    installCRDs: false
    podSecurityContext:
      enabled: true
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 100Mi
    serviceMonitor:
      enabled: true
      certManager:
        enabled: true
    certController:
      resources:
        requests:
          cpu: 10m
          memory: 128Mi
        limits:
          memory: 128Mi
    webhook:
      resources:
        requests:
          cpu: 10m
          memory: 100Mi
        limits:
          memory: 100Mi
