apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: victoria-metrics
spec:
  interval: 10m
  type: oci
  url: oci://ghcr.io/victoriametrics/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vmks
spec:
  interval: 10m
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      version: 0.33.1
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics
      interval: 10m
  valuesFrom:
    - kind: ConfigMap
      name: victoria-metrics-k8s-stack-values
      valuesKey: values.yaml
