apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - operator.yaml
  - repo.yaml

configMapGenerator:
  - name: victoria-metrics-k8s-stack-values
    options:
      disableNameSuffixHash: true
    files:
      - values.yaml=vm-k8s-stack-values.yaml
  - name: victoria-metrics-operator-values
    options:
      disableNameSuffixHash: true
    files:
      - values.yaml=operator-values.yaml
