---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: victoria-metrics-operator
spec:
  interval: 10m
  chart:
    spec:
      chart: victoria-metrics-operator
      version: 0.40.2
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics
      interval: 10m
  valuesFrom:
    - kind: ConfigMap
      name: victoria-metrics-operator-values
      valuesKey: values.yaml
