---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vmks
spec:
  interval: 10m
  dependsOn:
    - name: victoria-metrics-operator
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      version: 0.33.1
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics
      interval: 10m
  valuesFrom:
    - kind: ConfigMap
      name: victoria-metrics-k8s-stack-values
      valuesKey: values.yaml
