apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanagerConfig
metadata:
  name: robusta
  labels:
    alertmanager-config: global
spec:
  route:
    group_by: [ '...' ]
    group_wait: 1s
    group_interval: 1s
    repeat_interval: 4h
    receiver: 'robusta'
  receivers:
    - name:  'robusta'
      webhook_configs:
        - url: 'http://robusta-runner.robusta.svc.cluster.local/api/alerts'
          send_resolved: true
