---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: alloy
spec:
  interval: 10m
  chart:
    spec:
      chart: alloy
      version: 0.10.1
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 10m
  valuesFrom:
    - kind: ConfigMap
      name: alloy-values
      valuesKey: values.yaml
