---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: certificate-authority
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/certificate-authority/${ENVIRONMENT}
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-env
