---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: certificate-authority
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/certificate-authority/${CLUSTER_NAME}
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substitute:
      CLUSTER_NAME: ${CLUSTER_NAME}
      BASE_DOMAIN: ${BASE_DOMAIN}
    substituteFrom:
      - kind: Secret
        name: lets-encrypt-email