---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crossplane-addons
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/controllers/crossplane-addons/${ENVIRONMENT}
  targetNamespace: crossplane-system
  prune: true
  dependsOn:
    - name: crds
    - name: namespaces
    - name: crossplane
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-env
