---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: domain
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/domain/${CLUSTER_NAME}
  targetNamespace: crossplane-system
  prune: true
  dependsOn:
    - name: crossplane-addons
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-env
