---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: node-exporter
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/node-exporter/${ENVIRONMENT}
  prune: true
  dependsOn:
    - name: crds
  targetNamespace: kube-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-env
