---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocis
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes: ocis-data
    spec:
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: ocis
          image: ocis
          command: ["bash", "-c", "ocis server"]
          imagePullPolicy: IfNotPresent
          ports:
            - name: web
              containerPort: 9200
              protocol: TCP
            - name: metrics
              containerPort: 9205
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics
            timeoutSeconds: 5
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          envFrom:
            - secretRef:
                name: ocis-secrets
            - secretRef:
                name: ocis-s3-creds
            - configMapRef:
                name: ocis-env
          env:
            - name: SETTINGS_SERVICE_ACCOUNT_IDS
              value: "[$(SETTINGS_SERVICE_ACCOUNT_IDS)]"
            - name: OCIS_LDAP_BIND_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: attribute.key
                  name: ocis-ldap-token
          volumeMounts:
            - name: ldap-certs
              mountPath: /ldap-certs
            - name: ocis-config
              mountPath: /etc/ocis
            - name: ocis-data
              mountPath: /data/ocis
            - name: external-sites
              mountPath: /var/lib/ocis/web/assets/apps/external-sites
            - name: unzip
              mountPath: /var/lib/ocis/web/assets/apps/unzip
      restartPolicy: Always
      volumes:
        - name: ldap-certs
          secret:
            secretName: ocis-ldap-cert
            items:
              - key: ca.crt
                path: ca.crt
        - name: ocis-config
          configMap:
            name: ocis-config
        - name: ocis-data
          persistentVolumeClaim:
            claimName: ocis-data
        - name: external-sites
          configMap:
            name: external-sites
        - name: unzip
          configMap:
            name: unzip
# kubectl -n YOUR_POD_NAMESPACE annotate pod/YOUR_POD_NAME backup.velero.io/backup-volumes=YOUR_VOLUME_NAME_1,YOUR_VOLUME_NAME_2,...
