resources: [ ]

configMapGenerator:
  - literals:
      - OCIS_LDAP_URI=ldaps://ak-outpost-ocis.authentik.svc.cluster.local
      - OCIS_LDAP_BIND_DN="cn=ocis-ldap,ou=users,dc=ldap,dc=goauthentik,dc=io"
      - OCIS_LDAP_BIND_PASSWORD=set to secret
      - OCIS_LDAP_GROUP_BASE_DN="ou=groups,dc=ldap,dc=goauthentik,dc=io"
      - OCIS_LDAP_GROUP_FILTER="(objectclass=owncloud)"
      - OCIS_LDAP_GROUP_OBJECTCLASS="group"
      - OCIS_LDAP_USER_BASE_DN="dc=ldap,dc=goauthentik,dc=io"
      - OCIS_LDAP_USER_FILTER="(objectclass=owncloud)"
      - OCIS_LDAP_USER_OBJECTCLASS="user"
      - LDAP_LOGIN_ATTRIBUTES="uid"
      - OCIS_LDAP_SERVER_WRITE_ENABLED="false"
      - OCIS_EXCLUDE_RUN_SERVICES=idm
