resources:
  - deployment.yaml
  - pvc.yaml
  - secrets.yaml
  - ldap.yaml
  - service.yaml
  - external-sites
  - unzip

images:
  - name: ocis
    newName: owncloud/ocis
    newTag: 7.0.0

commonLabels:
  app.kubernetes.io/name: ocis
configMapGenerator:
  - name: ocis-config
    files:
      - ./config/proxy.yaml
      - ./config/csp.yaml
      - ./config/ocis.yaml
      - ./config/web.yaml
      - ./config/apps.yaml
  - name: ocis-env
    literals:
      # General Configuration
      - OCIS_URL=https://ocis.${BASE_DOMAIN}
      - OCIS_LOG_LEVEL=debug
      - OCIS_EXCLUDE_RUN_SERVICES=idp,idm
      - OCIS_BASE_DATA_PATH=/data/ocis
      # LDAP Configuration
      - OCIS_LDAP_URI=ldaps://ak-outpost-ocis.authentik.svc.cluster.local
      - OCIS_LDAP_CACERT=/ldap-certs/ca.crt
      - OCIS_LDAP_BIND_DN="cn=ldap-ocis,ou=users,dc=ldap,dc=goauthentik,dc=io"
      - OCIS_LDAP_SERVER_WRITE_ENABLED="false"
      - OCIS_LDAP_USER_BASE_DN="ou=users,dc=ldap,dc=goauthentik,dc=io"
      - OCIS_LDAP_GROUP_BASE_DN="ou=groups,dc=ldap,dc=goauthentik,dc=io"
      - OCIS_LDAP_USER_FILTER="(owncloud=true)"
      - OCIS_LDAP_GROUP_FILTER="(owncloud=true)"
      - OCIS_LDAP_USER_OBJECTCLASS=inetOrgPerson
      - OCIS_LDAP_GROUP_OBJECTCLASS=groupOfNames
      - OCIS_LDAP_USER_SCHEMA_ID=uid
      - OCIS_LDAP_USER_SCHEMA_USERNAME=cn
      - OCIS_LDAP_GROUP_SCHEMA_ID=uid
      - OCIS_LDAP_USER_SCHEMA_USER_TYPE=ownCloudUserType
      - OCIS_LDAP_USER_ENABLED_ATTRIBUTE=ownCloudUserEnabled
      - GRAPH_LDAP_SERVER_UUID="true"
      - GRAPH_ASSIGN_DEFAULT_USER_ROLE="true"
      # Proxy Configuration
      - PROXY_DEBUG_ADDR="0.0.0.0:9205"
      - PROXY_TLS="false"
      - PROXY_AUTOPROVISION_ACCOUNTS="false"
      - PROXY_ROLE_ASSIGNMENT_DRIVER=oidc
      - PROXY_OIDC_REWRITE_WELLKNOWN="true"
      - PROXY_USER_OIDC_CLAIM=sub
      - PROXY_USER_CS3_CLAIM=userid
      - PROXY_CSP_CONFIG_FILE_LOCATION=/etc/ocis/csp.yaml
      # OIDC Configuration
      - OCIS_OIDC_ISSUER=https://authentik.${BASE_DOMAIN}/application/o/ocis-application/
      - OCIS_OIDC_CLIENT_ID=ocis
      - WEB_OPTION_LOGOUT_URL="https://authentik.${BASE_DOMAIN}/if/user/#/settings;%7B%22page%22%3A%22page-sessions%22%7D"
      - WEB_ASSET_CORE_PATH=/var/lib/ocis/web/assets/core
      - WEB_ASSET_APPS_PATH=/var/lib/ocis/web/assets/apps
      - WEB_ASSET_THEMES_PATH=/var/lib/ocis/web/assets/themes
      # S3 Configuration
      - STORAGE_USERS_DRIVER=s3ng
      # keep system data on ocis storage since this are only small files atm
      - STORAGE_SYSTEM_DRIVER=ocis
      # s3ng specific settings
      - STORAGE_USERS_S3NG_ENDPOINT=https://nbg1.your-objectstorage.com
      - STORAGE_USERS_S3NG_REGION=default
      - STORAGE_USERS_S3NG_BUCKET=fzx-${ENVIRONMENT}-ocis
