---
apiVersion: applications.authentik.crossplane.io/v1alpha1
kind: LDAPProviderClaim
metadata:
  name: ocis
spec:
  externalHost: "ocis.staging-fzx-infra.dev"
  icon: "https://cdn.worldvectorlogo.com/logos/grafana.svg"
  description: "https://grafana.com/docs/grafana/latest/"
  redirectURL: /login/generic_oauth