apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ocis-data
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/ocis: enabled
    recurring-job.longhorn.io/ocis: enabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
