---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ocis-secrets
spec:
  secretStoreRef:
    name: cluster-store
    kind: ClusterSecretStore
  target:
    name: ocis-secrets
  data:
    - remoteRef:
        key: ocis-secrets
        property: OCIS_JWT_SECRET
      secretKey: OCIS_JWT_SECRET
    - remoteRef:
        key: ocis-secrets
        property: OCIS_MACHINE_AUTH_API_KEY
      secretKey: OCIS_MACHINE_AUTH_API_KEY
    - remoteRef:
        key: ocis-secrets
        property: OCIS_SYSTEM_USER_API_KEY
      secretKey: OCIS_SYSTEM_USER_API_KEY
    - remoteRef:
        key: ocis-secrets
        property: OCIS_TRANSFER_SECRET
      secretKey: OCIS_TRANSFER_SECRET
    - remoteRef:
        key: ocis-secrets
        property: OCIS_SYSTEM_USER_ID
      secretKey: OCIS_SYSTEM_USER_ID
    - remoteRef:
        key: ocis-secrets
        property: GRAPH_APPLICATION_ID
      secretKey: GRAPH_APPLICATION_ID
    - remoteRef:
        key: ocis-secrets
        property: OCIS_LDAP_BIND_PASSWORD
      secretKey: OCIS_LDAP_BIND_PASSWORD
    - remoteRef:
        key: ocis-secrets
        property: OCIS_SERVICE_ACCOUNT_ID
      secretKey: OCIS_SERVICE_ACCOUNT_ID
    - remoteRef:
        key: ocis-secrets
        property: OCIS_SERVICE_ACCOUNT_SECRET
      secretKey: OCIS_SERVICE_ACCOUNT_SECRET
    - remoteRef:
        key: ocis-secrets
        property: OCIS_SERVICE_ACCOUNT_ID
      secretKey: SETTINGS_SERVICE_ACCOUNT_IDS
    - remoteRef:
        key: ocis-secrets
        property: STORAGE_USERS_MOUNT_ID
      secretKey: STORAGE_USERS_MOUNT_ID
    - remoteRef:
        key: ocis-secrets
        property: STORAGE_USERS_MOUNT_ID
      secretKey: GATEWAY_STORAGE_USERS_MOUNT_ID
    - remoteRef:
        key: ocis-secrets
        property: IDM_SVC_PASSWORD
      secretKey: IDM_SVC_PASSWORD
    - remoteRef:
        key: ocis-secrets
        property: IDM_SVC_PASSWORD
      secretKey: GRAPH_LDAP_BIND_PASSWORD
    - remoteRef:
        key: ocis-secrets
        property: IDM_REVASVC_PASSWORD
      secretKey: IDM_REVASVC_PASSWORD
    - remoteRef:
        key: ocis-secrets
        property: IDM_REVASVC_PASSWORD
      secretKey: USERS_LDAP_BIND_PASSWORD
    - remoteRef:
        key: ocis-secrets
        property: IDM_REVASVC_PASSWORD
      secretKey: GROUPS_LDAP_BIND_PASSWORD
    - remoteRef:
        key: ocis-secrets
        property: IDM_IDPSVC_PASSWORD
      secretKey: IDM_IDPSVC_PASSWORD
    - remoteRef:
        key: ocis-secrets
        property: THUMBNAILS_TRANSFER_TOKEN
      secretKey: THUMBNAILS_TRANSFER_TOKEN
    - remoteRef:
        key: ocis-secrets
        property: COLLABORATION_WOPI_SECRET
      secretKey: COLLABORATION_WOPI_SECRET
