---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: whoami-tls-certificate
spec:
  secretName: tls-whoami-ingress
  issuerRef:
    name: dns-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - whoami.${BASE_DOMAIN}
