---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: whoami-tls-certificate
spec:
  secretName: tls-whoami-ingress
  issuerRef:
    name: http-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - static.19.109.235.167.clients.your-server.de
