---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whoami
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`static.19.109.235.167.clients.your-server.de`)
      kind: Rule
      services:
        - name: whoami
          port: 9000
      middlewares:
        - name: redirect-https
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-tls
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  tls:
    secretName: tls-whoami-ingress
  routes:
    - match: Host(`static.19.109.235.167.clients.your-server.de`)
      kind: Rule
      services:
        - name: whoami
          port: 9000
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
spec:
  redirectScheme:
    scheme: https
    permanent: true
