apiVersion: provider.authentik.crossplane.io/v1alpha1
kind: Proxy
metadata:
  name: cluster-admins
spec:
  deletionPolicy: Delete
  forProvider:
    attributes: '{}'
    isSuperuser: false
    name: cluster-admins
  initProvider: { }
  managementPolicies:
    - '*'
status:
  atProvider:
    attributes: '{}'
    id: cabab51f-a3b7-46fc-bdad-9c3488492397
    isSuperuser: false
    name: cluster-admins
    users:
      - 34
