---
apiVersion: directory.authentik.crossplane.io/v1alpha1
kind: Group
metadata:
  name: cluster-admins
  labels:
    velero.io/include: "true"
  annotations:
    crossplane.io/external-name: cabab51f-a3b7-46fc-bdad-9c3488492397
spec:
  forProvider:
    name: cluster-admins
    isSuperuser: false
---
apiVersion: directory.authentik.crossplane.io/v1alpha1
kind: Group
metadata:
  name: grafana-editors
  labels:
    velero.io/include: "true"
  annotations:
    crossplane.io/external-name: 7552a0a9-4444-4ee0-b783-45b9e1145993
spec:
  forProvider:
    name: grafana-editors
    isSuperuser: false
---
apiVersion: directory.authentik.crossplane.io/v1alpha1
kind: Group
metadata:
  name: grafana-viewers
  labels:
    velero.io/include: "true"
  annotations:
    crossplane.io/external-name: 1e2c917d-57fc-4daf-9e39-9629112e38a9
spec:
  forProvider:
    name: grafana-viewers
    isSuperuser: false
