---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: robusta
  namespace: robusta
spec:
  chart:
    spec:
      chart: robusta
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: robusta
      version: 0.20.0
  interval: 1m0s
  values:
    globalConfig:
      check_prometheus_flags: false
      signing_key: '{{ env.SIGNING_KEY }}'
      account_id: '{{ env.ACCOUNT_ID }}'
      alertmanager_url: "http://vmalertmanager-vmks-victoria-metrics-k8s-stack.observability.svc.cluster.local:9093"
      grafana_url: ""
      prometheus_url: "http://vmsingle-vmks-victoria-metrics-k8s-stack.observability.svc.cluster.local:8429"
    clusterName: ${ENVIRONMENT}
    sinksConfig:
      - robusta_sink:
          name: robusta_ui_sink
          token: '{{ env.ROBUSTA_UI_TOKEN }}'
      - slack_sink:
          name: main_slack_sink
          slack_channel: alerts
          api_key: '{{ env.SLACK_API_KEY }}'
    enablePrometheusStack: false
    enablePlatformPlaybooks: true
    enableHolmesGPT: true
    holmes:
      resources:
        limits:
          memory: 640Mi
        requests:
          cpu: 10m
          memory: 640Mi
      additionalEnvVars:
        - name: ROBUSTA_AI
          value: "true"
        - name: ROBUSTA_ACCOUNT_ID
          valueFrom:
            secretKeyRef:
              name: robusta-secrets
              key: ACCOUNT_ID
        - name: ROBUSTA_UI_TOKEN
          valueFrom:
            secretKeyRef:
              name: robusta-secrets
              key: ROBUSTA_UI_TOKEN
    kubewatch:
      resources:
        limits:
          cpu: null
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
      securityContext:
        container:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsUser: 1000
        pod:
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
    runner:
      sendAdditionalTelemetry: false
      additional_env_froms:
        - secretRef:
            name: robusta-secrets
      resources:
        limits:
          cpu: null
          memory: 640Mi
        requests:
          cpu: 250m
          memory: 640Mi
      securityContext:
        container:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsUser: 65534
        pod:
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
