apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: robusta-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-store
  target:
    name: robusta-secrets
  data:
    - secretKey: SIGNING_KEY
      remoteRef:
        property: SIGNING_KEY
        key: robusta
    - secretKey: ACCOUNT_ID
      remoteRef:
        property: username
        key: robusta
    - secretKey: SLACK_API_KEY
      remoteRef:
        property: SLACK_API_KEY
        key: robusta
    - secretKey: ROBUSTA_UI_TOKEN
      remoteRef:
        property: ROBUSTA_UI_TOKEN
        key: robusta
