---
apiVersion: dns.cloudflare.crossplane.io/v1alpha1
kind: Record
metadata:
  name: cluster-domain-cname
spec:
  forProvider:
    name: "${BASE_DOMAIN}"
    content: ${CLUSTER_NAME}.${BASE_DOMAIN}
    ttl: 3600
    type: CNAME
    zoneIdRef:
      name: root-domain
---
apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: cluster-root-domain-dns-record-ip-v4
spec:
  deletionPolicy: Delete
  readiness:
    policy: AllTrue
  references:
    - patchesFrom:
        apiVersion: v1
        kind: Service
        name: traefik
        namespace: traefik
        fieldPath: status.loadBalancer.ingress[0].ip
      toFieldPath: spec.forProvider.content
  forProvider:
    manifest:
      apiVersion: dns.cloudflare.crossplane.io/v1alpha1
      kind: Record
      metadata:
        name: cluster-domain-ip-v4-cluster-1
      spec:
        forProvider:
          name: "cluster-1.${BASE_DOMAIN}"
          ttl: 3600
          type: A
          zoneIdRef:
            name: root-domain
---
apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: cluster-root-domain-dns-record-ip-v6
spec:
  deletionPolicy: Delete
  readiness:
    policy: AllTrue
  references:
    - patchesFrom:
        apiVersion: v1
        kind: Service
        name: traefik
        namespace: traefik
        fieldPath: status.loadBalancer.ingress[1].ip
      toFieldPath: spec.forProvider.content
  forProvider:
    manifest:
      apiVersion: dns.cloudflare.crossplane.io/v1alpha1
      kind: Record
      metadata:
        name: cluster-domain-ip-v6-cluster-1
      spec:
        forProvider:
          name: "cluster-1.${BASE_DOMAIN}"
          ttl: 3600
          type: AAAA
          zoneIdRef:
            name: root-domain