apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hcloud-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-store
  target:
    name: hcloud-token
  data:
    - secretKey: token
      remoteRef:
        property: password
        key: hcloud-token
