---
apiVersion: applications.authentik.crossplane.io/v1alpha1
kind: OAuthClaim
metadata:
  name: grafana
spec:
  externalHost: "grafana.${BASE_DOMAIN}"
  clusterName: ${CLUSTER_NAME}
  icon: "https://cdn.worldvectorlogo.com/logos/grafana.svg"
  description: "https://grafana.com/docs/grafana/latest/"
  redirectURL: /login/generic_oauth
  adminBinding: false
  backendService:
    name: grafana-service
    port: 3000
  headers:
    csp: "script-src 'self' 'unsafe-eval' 'unsafe-inline' ;object-src 'none';font-src 'self';style-src 'self' 'unsafe-inline' blob:;img-src * data:;base-uri 'self';connect-src 'self' grafana.com ws://grafana.${BASE_DOMAIN} wss://grafana.${BASE_DOMAIN};manifest-src 'self';media-src 'none';form-action 'self';"
