---
apiVersion: applications.authentik.crossplane.io/v1alpha1
kind: OAuthClaim
metadata:
  name: grafana
spec:
  externalHost: "grafana.${BASE_DOMAIN}"
  icon: "https://cdn.worldvectorlogo.com/logos/grafana.svg"
  description: "https://grafana.com/docs/grafana/latest/"
  redirectURL: /login/generic_oauth
  adminBinding: false
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-tls-certificate
spec:
  secretName: tls-grafana-ingress
  secretTemplate:
    labels:
      velero.io/include: "true"
  issuerRef:
    name: dns-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - grafana.${BASE_DOMAIN}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: grafana-gateway
spec:
  gatewayClassName: traefik
  listeners:
    - name: websecure
      port: 8443
      protocol: HTTPS
      hostname: grafana.${BASE_DOMAIN}
      tls:
        certificateRefs:
          - name: tls-grafana-ingress  # <==== Use the name defined in Certificate resource.
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana-http
spec:
  parentRefs:
    - name: grafana-gateway
  hostnames:
    - grafana.${BASE_DOMAIN}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: grafana-service
          port: 3000
          weight: 1

