apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: victoria-metrics
resources:
  - operator.yaml
  - repo.yaml

configMapGenerator:
  - name: victoria-metrics-operator-values
    files:
      - values.yaml=operator-values.yaml

configurations:
  - kustomize-configurations.yaml