---
apiVersion: authentik.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: crossplane-authentik
      namespace: crossplane-system
      key: credentials
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: crossplane-authentik
spec:
  secretStoreRef:
    name: cluster-store
    kind: ClusterSecretStore
  target:
    name: crossplane-authentik
    template:
      data:
        credentials: |
          {
            "url": "http://authentik-server.authentik.svc.cluster.local",
            "token": "{{ .token }}",
            "insecure": "true"
          }
  data:
    - secretKey: token
      remoteRef:
        key: authentik-bootstrap-token
        property: password
