apiVersion: authentik.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: authentik-provider
spec:
  credentials:
    source: Secret
    secretRef:
      name: crossplane-authentik
      namespace: crossplane-system
      key: credentials
---
apiVersion: authentik.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: crossplane-authentik
      namespace: crossplane-system
      key: credentials
