---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare
spec:
  secretStoreRef:
    name: cluster-store
    kind: ClusterSecretStore
  target:
    name: cloudflare
    template:
      data:
        credentials: |
          {
            "api_token": "{{ .token }}"
          }
  data:
    - secretKey: token
      remoteRef:
        key: cloudflare-domain-edit
        property: password
---
apiVersion: cloudflare.cloudflare.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: cloudflare
      namespace: crossplane-system
      key: credentials
