---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-credentials
spec:
  secretStoreRef:
    name: cluster-store
    kind: ClusterSecretStore
  target:
    name: cloudflare-credentials
  data:
    - secretKey: token
      remoteRef:
        key: cloudflare-domain-edit
        property: password
    - secretKey: email
      remoteRef:
        key: cloudflare-domain-edit
        property: username
