---
apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: cloudflare-terraform
spec:
  credentials:
    - secretRef:
        key: token
        name: cloudflare-credentials
        namespace: crossplane-system
      source: Secret
      filename: cloudflare-api-token
    - secretRef:
        key: email
        name: cloudflare-credentials
        namespace: crossplane-system
      source: Secret
      filename: cloudflare-email
  configuration: |
    terraform {
      required_providers {
        cloudflare = {
          source  = "cloudflare/cloudflare"
          version = "~> 4.0"
        }
      }
    }
    
    provider "cloudflare" {
      api_token = file("cloudflare-api-token")
      email = file("cloudflare-email")
    }

    // Modules _must_ use remote state. The provider does not persist state.
    terraform {
      backend "kubernetes" {
        secret_suffix     = "providerconfig-cloudflare-terraform"
        namespace         = "crossplane-system"
        in_cluster_config = true
      }
    }
