---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cloudnative-pg
spec:
  interval: 10m
  url: https://cloudnative-pg.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudnative-pg
spec:
  interval: 10m
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.23.0
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
      interval: 10m
  valuesFrom:
    - kind: ConfigMap
      name: cloudnative-pg-values
