apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
  - image-catalog.yaml
  - dashboard.yaml
configMapGenerator:
  - name: cloudnative-pg-values
    files:
      - values.yaml=values.yaml

configurations:
  - kustomize-configurations.yaml
