global:
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

alloy:
  configMap:
    create: false
    name: alloy-config
    key: config.alloy
  enableReporting: false
  securityContext:
    runAsUser: 473
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    privileged: false
    readOnlyRootFilesystem: false
  resources:
    limits:
      memory: 150Mi
    requests:
      cpu: 50m
      memory: 150Mi

configReloader:
  enabled: true
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    privileged: false
    readOnlyRootFilesystem: false
  resources:
    limits:
      memory: 10Mi
    requests:
      cpu: 50m
      memory: 10Mi

controller:
  type: 'statefulset'
  enableStatefulSetAutoDeletePVC: true
  volumeClaimTemplates: []

serviceMonitor:
  enabled: true
