apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system

patches:
  - target:
      kind: Deployment
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          limits:
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 64Mi
#  - path: patches.yaml
#    target:
#      kind: Deployment