---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-controller
spec:
  template:
    spec:
      containers:
        - name: manager
          resources:
           limits:
             memory: 100Mi
           requests:
             cpu: 10m
             memory: 64Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-controller
spec:
  template:
    spec:
      containers:
        - name: manager
          resources:
            limits:
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 64Mi
