---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-store
spec:
  provider:
    onepassword:
      connectHost: http://op-connect.external-secrets.svc.cluster.local:8080
      vaults:
        kubernetes-staging: 1  # look in this vault first
      auth:
        secretRef:
          connectTokenSecretRef:
            namespace: external-secrets
            name: op-connect-token
            key: token