---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-database
  labels:
    app.kubernetes.io/part-of: authentik
    app.kubernetes.io/component: database
  annotations:
    terasky.backstage.io/component-type: resource
spec:
  backup:
    barmanObjectStore:
      destinationPath: "s3://fzx-staging-postgres/backup-authentik-v3"
  externalClusters:
    - name: clusterBackup
      barmanObjectStore:
        destinationPath: "s3://fzx-staging-postgres/backup-authentik-v2"
        endpointURL: https://nbg1.your-objectstorage.com
        serverName: authentik-database
        s3Credentials:
          accessKeyId:
            name: hetzner-object-store
            key: access_key
          secretAccessKey:
            name: hetzner-object-store
            key: secret_key
