apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: fluxcd
spec:
  namespaceSelector:
    matchNames:
      - flux-system
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - helm-controller
          - source-controller
          - kustomize-controller
          - notification-controller
          - image-automation-controller
          - image-reflector-controller
  podMetricsEndpoints:
    - port: http-prom
      relabelConfigs:
        - sourceLabels:
            - __meta_kubernetes_pod_phase
          action: keep
          regex: Running
