apiVersion: v1
kind: Service
metadata:
  name: traefik-admin
spec:
  selector:
    app.kubernetes.io/instance: traefik-traefik
    app.kubernetes.io/name: traefik
  ports:
    - protocol: TCP
      port: 8080
      targetPort: traefik
      name: traefik
  type: ClusterIP
