apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - traefik-release.yaml
  - dashboard.yaml
  - ingress.yaml

configMapGenerator:
  - name: traefik-values
    files:
      - values.yaml=values.yaml

configurations:
  - kustomize-configurations.yaml