apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 10m
  url: https://helm.traefik.io/traefik
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: '33.2.1'
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
      interval: 10m
  valuesFrom:
    - kind: ConfigMap
      name: traefik-values
