image:
  tag: v3.2.2

gatewayClass:
  enabled: true

gateway:
  enabled: false

ingressRoute:
  dashboard:
    enabled: true

providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
    ingressClass: traefik
  kubernetesIngress:
    enabled: true
    ingressClass: traefik
  kubernetesGateway:
    enabled: true

logs:
  general:
    format: common
    level: "INFO"
  access:
    enabled: true
    format: common

metrics:
  prometheus:
    service:
      enabled: true
    serviceMonitor:
      enabled: true
      metricRelabelings:
        - sourceLabels: [ __name__ ]
          separator: ;
          regex: ^fluentd_output_status_buffer_(oldest|newest)_.+
          replacement: $1
          action: drop
    prometheusRule:
      enabled: true
      rules:
        - alert: TraefikDown
          expr: up{job="traefik"} == 0
          for: 5m
          labels:
            context: traefik
            severity: warning
          annotations:
            summary: "Traefik Down"
            description: "{{ $labels.pod }} on {{ $labels.nodename }} is down"

# set to empty array to disable calling home
globalArguments: [ ]

ports:
  web:
    redirectTo:
      port: websecure
    forwardedHeaders:
      trustedIPs:
        - 127.0.0.1/32
        - 10.0.0.0/16
    proxyProtocol:
      trustedIPs:
        - 127.0.0.1/32
        - 10.0.0.0/16

  websecure:
    forwardedHeaders:
      trustedIPs:
        - 127.0.0.1/32
        - 10.0.0.0/16
    proxyProtocol:
      trustedIPs:
        - 127.0.0.1/32
        - 10.0.0.0/16
      default: true

service:
  enabled: true
  type: LoadBalancer
  annotations:
    "load-balancer.hetzner.cloud/algorithm-type": "least_connections"
    "load-balancer.hetzner.cloud/disable-private-ingress": "true"
    load-balancer.hetzner.cloud/disable-public-network: "false"
    "load-balancer.hetzner.cloud/health-check-interval": "15s"
    "load-balancer.hetzner.cloud/health-check-retries": "3"
    "load-balancer.hetzner.cloud/health-check-timeout": "10s"
    load-balancer.hetzner.cloud/ipv6-disabled: "false"
    "load-balancer.hetzner.cloud/location": "nbg1"
    "load-balancer.hetzner.cloud/private-ipv4": "10.0.64.252"
    "load-balancer.hetzner.cloud/name": "${ENVIRONMENT}-ingress"
    "load-balancer.hetzner.cloud/type": "lb11"
    "load-balancer.hetzner.cloud/use-private-ip": "true"
    "load-balancer.hetzner.cloud/uses-proxyprotocol": "true"
resources:
  limits:
    memory: 128Mi
  requests:
    cpu: 30m
    memory: 128Mi
podSecurityContext:
  seccompProfile:
    type: RuntimeDefault
